### ISSUE TITLE
Request: CustomiseOxygen also fillable at fabricator when set to autofill

### ISSUE THREAD

**Issue by Gordon-Dry** [DaWrecka/Beta-Mods#1]
Can you make that the scuba tanks can be filled at the fabricator with the higher capacity settings also when the auto fill is enabled, so have it additionally to being auto filled in the air?

**Comment by DaWrecka** [comment]
That goes against the intention of the mod. If you want auto-refill tanks to have higher capacities, just increase the base multiplier, or set up overrides in the configuration file.
