### ISSUE TITLE
When refilling scuba tank at fabricator, a black cube is added to the inventory each time

### ISSUE THREAD

**Issue by Gordon-Dry** [DaWrecka/Beta-Mods#2]

**Comment by DaWrecka** [comment]
I need more information. I need a log, maybe even a screenshot. Additionally, if you're using UI Tweaks, I need you to update it.

**Comment by Gordon-Dry** [comment]
Inside the inventory UI at refilling the tank a new small 1x1 scuba tank is added each time, when I dropped them outside the base they were black cubes.

I will update UI Tweaks and see again.

**Comment by Gordon-Dry** [comment]
Now it seems fixed, there is still a black cube on the fabricator but no more small 1x1 tank added to the inventory and the tank is properly filled.
Closing for now.
